export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const WINE_REQUEST = 'WINE_REQUEST';
export const WINE_SUCCESS = 'WINE_SUCCESS';
export const WINE_LIST_SUCCESS = 'WINE_LIST_SUCCESS';
export const WINE_REVIEWS_SUCCESS = 'WINE_REVIEWS_SUCCESS';
export const WINE_MESSAGE = 'WINE_MESSAGE';
export const WINE_ERROR = 'WINE_ERROR';
